# Generated by Django 4.0.1 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_member_id_roommember_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(db_index=True, max_length=200)),
                ('uid', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='roommember',
            constraint=models.UniqueConstraint(fields=('uid', 'room_name'), name='unique_member_per_room'),
        ),
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['room_name'], name='base_roomme_room_na_3d942f_idx'),
        ),
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['uid', 'room_name'], name='base_roomme_uid_1bf002_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room_name', 'id'], name='base_chatme_room_na_e24b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='base_chatme_created_5dd996_idx'),
        ),
    ]
