# Generated by Django 4.0.1 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_chatmessage_roommember_constraints'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='base_chatme_room_na_e24b4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='base_chatme_created_5dd996_idx',
        ),
        migrations.RemoveIndex(
            model_name='roommember',
            name='base_roomme_room_na_3d942f_idx',
        ),
        migrations.RemoveIndex(
            model_name='roommember',
            name='base_roomme_uid_1bf002_idx',
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room_name', 'id'], name='base_chatme_room_na_ad960f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='base_chatme_created_0aeb4f_idx'),
        ),
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['room_name'], name='base_roomme_room_na_de3bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['uid', 'room_name'], name='base_roomme_uid_c8d45b_idx'),
        ),
    ]
